FROM gradle:jdk11 as builder
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle shadowjar

FROM adoptopenjdk/openjdk11-openj9:alpine-slim
LABEL author="Sofus Albertsen"
COPY --from=builder /home/gradle/src/build/libs/app-*-all.jar app.jar
EXPOSE 8000
CMD java -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar app.jar