# Find the image for dotnet core (hint its microsoft image on dockerhub)
# Add the razorpage folder to /app in the container
# Final tip: Dotnet needs a specific environmental variable, 
# which I am going to give you since its an implementation specific thing. 
#
# ENV ASPNETCORE_URLS http://*:5000


# happy coding !
FROM hello-world 
