# Dockerfile for docker-bottle web application

# Add a base image to build this image off of
FROM 
COPY 
# Add a default port containers from this image should expose
EXPOSE 

# Add a default command for this image
CMD 
